_BASE_: [ "../_base_/M2F.yaml", "../_base_/SwinL.yaml", "../_base_/YTVIS2019.yaml"]
MODEL:
  META_ARCHITECTURE: "CTVISModel"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "CLMultiScaleMaskedTransformerDecoder"
    NUM_OBJECT_QUERIES: 200
  TRACKER:
    TRACKER_NAME: "SimpleTracker"
    MEMORY_BANK:
      EMBED_TYPE: "similarity_guided"
    MATCH_SCORE_THR: 0.3
  CL_PLUGIN:
    CL_PLUGIN_NAME: "CTCLPlugin"
    REID_WEIGHT: 2.
    AUX_REID_WEIGHT: 3.
    NUM_NEGATIVES: 199
INPUT:
  SAMPLING_FRAME_NUM: 8
  SAMPLING_FRAME_RANGE: 16
